# Generated by Django 4.2.20 on 2025-03-28 20:33

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Favorite',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('meal_id', models.CharField(max_length=10)),
                ('meal_name', models.CharField(max_length=100)),
                ('meal_thumb', models.URLField()),
                ('date_added', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
